services:
  # Database
  postgres:
    image: postgres:15
    container_name: flashcard-db
    environment:
      POSTGRES_USER: flashcard_user
      POSTGRES_PASSWORD: flashcard_password
      POSTGRES_DB: flashcard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flashcard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flashcard_user -d flashcard_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: flashcard-api
    environment:
      DATABASE_URL: "postgresql://flashcard_user:flashcard_password@postgres:5432/flashcard_db"
      AT_SECRET: "your-super-secret-access-token-key-change-in-production"
      RT_SECRET: "your-super-secret-refresh-token-key-change-in-production"
      BACKEND_PORT: 3000
      FRONTEND_URL: "http://localhost:3000"
      NODE_ENV: "production"
    ports:
      - "4002:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - flashcard-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flashcard-frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:4002
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - flashcard-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  flashcard-network:
    driver: bridge