-- AlterTable
ALTER TABLE "set" ADD COLUMN     "color" TEXT NOT NULL DEFAULT '#552583',
ADD COLUMN     "lastAccess" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "cardStudied" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "correct" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "hashedRt" TEXT;
